version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-cli-version: latest
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: myContext
          create-repo: true
          dockerfile: myDockerfile
          executor: aws-ecr/default
          extra-build-args: '--compress'
          new-profile-name: newProfileName
          no-output-timeout: 20m
          path: pathToMyDockerfile
          platform: linux/amd64
          profile-name: myProfileName
          public-registry: false
          push-image: true
          region: AWS_REGION
          registry-id: AWS_ECR_REGISTRY_ID
          repo: myECRRepository
          repo-scan-on-push: true
          role-arn: 'arn:aws:iam::123456789012:role/testing'
          skip-when-tags-exist: false
          source-profile: sourceProfileName
          tag: 'latest,myECRRepoTag'