version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          executor: aws-ecr/default
          path: .
          platform: linux/amd64
          push-image: true
          region: ${AWS_REGION}
          registry-id: AWS_REGISTRY
          repo: testing
          tag: 'latest'





